### ISSUE TITLE
Global install needs to be rebuilt by electron-rebuild.

### ISSUE THREAD

**Issue by MPolymath** [spacebro/spacebro#15]
Launching spacebro after a global install gives me the following errors.

```
spacebro
module.js:341
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mina/.nvm/versions/node/v5.12.0/lib/node_modules/spacebro/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)

```

**Comment by hugohil** [comment]
Can you provide the command used, node version, npm/yarn version and OS please ? Also are you using nvm ? Maybe avm ?
Thanks

**Comment by MPolymath** [comment]
Yes thank you, I used the following:

command: npm install -g spacebro
node: v5.12.0

The issue is however fixed as I no longer have the error after installing
spacebro on node: v6.9.1.
